### ISSUE TITLE
CEPH can't create cluster

### ISSUE THREAD

**Issue by larcohex** [subutai-attic/peer-os-plugins#40]
For replay this bug you need:

Test case
1) Go to SS -> Bazaar and install Ceph plugin.
2) Go to Environment -> click on 'plugin' icon -> choose ceph plugin and create an environment.
3) Go to Ceph plugin -> put 'testClas' in cluster field and click on 'Create' button.

Result: you can observe Error message
![screenshot from 2016-04-22 14 12 36](https://cloud.githubusercontent.com/assets/11311924/14735682/4c5772a6-0894-11e6-8b02-4d0e45edba91.png)

**Comment by dilshat** [comment]
Update scripts for CEPH please

**Comment by tzununbekov** [comment]
@Dilshat stuck on the first step, cannot find Ceph plugin in Bazaar. Was the plugin removed?

**Comment by dilshat** [comment]
@eabyshev  @larcohex where is plugin?

**Comment by larcohex** [comment]
we didn't upload plugin because of this issue, will upload it

**Comment by larcohex** [comment]
uploaded

**Comment by tzununbekov** [comment]
@Dilshat @eabyshev @larcohex ceph template updated on cdn, please check

**Comment by larcohex** [comment]
@tzununbekov output of `ceph.sh`

```
root@40b428c0-058e-422c-b568-a212978d1417:/# bash /etc/ceph/ceph.sh 
Warning: Permanently added 'edbfc9c0-8b57-49b5-bfc3-9be26b2d2580,172.16.14.2' (ECDSA) to the list of known hosts.
Warning: Permanently added '6694a60d-b4ea-46eb-ae70-7972f5b3012b,172.16.14.4' (ECDSA) to the list of known hosts.
Warning: Permanently added '40b428c0-058e-422c-b568-a212978d1417,172.16.14.3' (ECDSA) to the list of known hosts.
Traceback (most recent call last):
  File "/usr/bin/ceph-deploy", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/util/decorators.py", line 62, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 100, in main
    parser = get_parser()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 87, in get_parser
    p.set_defaults(cd_conf = ceph_deploy.conf.cephdeploy.load())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 63, in load
    parser.read(location())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 58, in location
    return _locate_or_create()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 78, in _locate_or_create
    create_stub(home_config)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 84, in create_stub
    with open(_path, 'w') as cd_conf:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/apps/subutai/IVXWPVCecGFO/.cephdeploy.conf'
ceph-mon.conf                                 100%  691     0.7KB/s   00:00    
ceph-osd.conf                                 100% 1775     1.7KB/s   00:00    
ceph-mon.conf                                 100%  691     0.7KB/s   00:00    
ceph-osd.conf                                 100% 1775     1.7KB/s   00:00    
ceph-mon.conf                                 100%  691     0.7KB/s   00:00    
ceph-osd.conf                                 100% 1775     1.7KB/s   00:00    
Traceback (most recent call last):
  File "/usr/bin/ceph-deploy", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/util/decorators.py", line 62, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 100, in main
    parser = get_parser()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 87, in get_parser
    p.set_defaults(cd_conf = ceph_deploy.conf.cephdeploy.load())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 63, in load
    parser.read(location())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 58, in location
    return _locate_or_create()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 78, in _locate_or_create
    create_stub(home_config)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 84, in create_stub
    with open(_path, 'w') as cd_conf:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/apps/subutai/IVXWPVCecGFO/.cephdeploy.conf'
Traceback (most recent call last):
  File "/usr/bin/ceph-deploy", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/util/decorators.py", line 62, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 100, in main
    parser = get_parser()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 87, in get_parser
    p.set_defaults(cd_conf = ceph_deploy.conf.cephdeploy.load())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 63, in load
    parser.read(location())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 58, in location
    return _locate_or_create()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 78, in _locate_or_create
    create_stub(home_config)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 84, in create_stub
    with open(_path, 'w') as cd_conf:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/apps/subutai/IVXWPVCecGFO/.cephdeploy.conf'
Traceback (most recent call last):
  File "/usr/bin/ceph-deploy", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/util/decorators.py", line 62, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 100, in main
    parser = get_parser()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 87, in get_parser
    p.set_defaults(cd_conf = ceph_deploy.conf.cephdeploy.load())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 63, in load
    parser.read(location())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 58, in location
    return _locate_or_create()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 78, in _locate_or_create
    create_stub(home_config)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 84, in create_stub
    with open(_path, 'w') as cd_conf:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/apps/subutai/IVXWPVCecGFO/.cephdeploy.conf'
Traceback (most recent call last):
  File "/usr/bin/ceph-deploy", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/util/decorators.py", line 62, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 100, in main
    parser = get_parser()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 87, in get_parser
    p.set_defaults(cd_conf = ceph_deploy.conf.cephdeploy.load())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 63, in load
    parser.read(location())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 58, in location
    return _locate_or_create()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 78, in _locate_or_create
    create_stub(home_config)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 84, in create_stub
    with open(_path, 'w') as cd_conf:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/apps/subutai/IVXWPVCecGFO/.cephdeploy.conf'
Traceback (most recent call last):
  File "/usr/bin/ceph-deploy", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/util/decorators.py", line 62, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 100, in main
    parser = get_parser()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 87, in get_parser
    p.set_defaults(cd_conf = ceph_deploy.conf.cephdeploy.load())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 63, in load
    parser.read(location())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 58, in location
    return _locate_or_create()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 78, in _locate_or_create
    create_stub(home_config)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 84, in create_stub
    with open(_path, 'w') as cd_conf:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/apps/subutai/IVXWPVCecGFO/.cephdeploy.conf'
Traceback (most recent call last):
  File "/usr/bin/ceph-deploy", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/util/decorators.py", line 62, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 100, in main
    parser = get_parser()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 87, in get_parser
    p.set_defaults(cd_conf = ceph_deploy.conf.cephdeploy.load())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 63, in load
    parser.read(location())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 58, in location
    return _locate_or_create()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 78, in _locate_or_create
    create_stub(home_config)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 84, in create_stub
    with open(_path, 'w') as cd_conf:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/apps/subutai/IVXWPVCecGFO/.cephdeploy.conf'
Traceback (most recent call last):
  File "/usr/bin/ceph-deploy", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/util/decorators.py", line 62, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 100, in main
    parser = get_parser()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/cli.py", line 87, in get_parser
    p.set_defaults(cd_conf = ceph_deploy.conf.cephdeploy.load())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 63, in load
    parser.read(location())
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 58, in location
    return _locate_or_create()
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 78, in _locate_or_create
    create_stub(home_config)
  File "/usr/lib/python2.7/dist-packages/ceph_deploy/conf/cephdeploy.py", line 84, in create_stub
    with open(_path, 'w') as cd_conf:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/apps/subutai/IVXWPVCecGFO/.cephdeploy.conf'
```

**Comment by tzununbekov** [comment]
@larcohex 

> /home/ubuntu/apps/subutai/IVXWPVCecGFO/.cephdeploy.conf

such output means that system environment uses RH's variables which causes problem. Switch environment by running `sudo su` or call scripts with `sudo` prefix
