### ISSUE TITLE
[AppScale] Can't open the AS console if installed on x-peer

### ISSUE THREAD

**Issue by asanaliev** [subutai-attic/peer-os-plugins#48]
My both testing AS on x-peer failed (SS only, w/o Hub). I got this error when opening the AS console:

![image](https://cloud.githubusercontent.com/assets/7465404/15808288/b828d0dc-2b95-11e6-98c0-1d09ec89a227.png)

Karaf logs:
`2016-06-05 21:19:33,781 | ERROR | pool-98-thread-3 | LocalPeerImpl                    | 181 - io.subutai.core.localpeer.impl - 4.0.0.RC14-SNAPSHOT | Command failed: time="2016-06-05 21:19:33" level=fatal msg="Reloading nginx, exit status 1"
, FAILED
io.subutai.core.network.api.NetworkManagerException: Command failed: time="2016-06-05 21:19:33" level=fatal msg="Reloading nginx, exit status 1"
, FAILED
    at io.subutai.core.network.impl.NetworkManagerImpl.execute(NetworkManagerImpl.java:365)[172:io.subutai.core.network.impl:4.0.0.RC14-SNAPSHOT]
    at io.subutai.core.network.impl.NetworkManagerImpl.setVlanDomain(NetworkManagerImpl.java:254)[172:io.subutai.core.network.impl:4.0.0.RC14-SNAPSHOT]
    at Proxyf97daa60_0d35_4492_915f_a9362a4414d2.setVlanDomain(Unknown Source)[:]
    at io.subutai.core.localpeer.impl.LocalPeerImpl.addReverseProxy(LocalPeerImpl.java:2321)[181:io.subutai.core.localpeer.impl:4.0.0.RC14-SNAPSHOT]
    at Proxy6c7b9bfa_2e93_4648_bb95_be5a8c5ae3c1.addReverseProxy(Unknown Source)[:]
    at Proxy6c7b9bfa_2e93_4648_bb95_be5a8c5ae3c1.addReverseProxy(Unknown Source)[:]
    at Proxyda45de01_5b81_4111_8bb5_4c022278622f.addReverseProxy(Unknown Source)[:]
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.configureRH(ClusterConfiguration.java:147)[286:io.subutai.plugin.appscale.impl:4.0.0.RC14-SNAPSHOT]
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.installCluster(ClusterConfiguration.java:107)[286:io.subutai.plugin.appscale.impl:4.0.0.RC14-SNAPSHOT]
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.configureCluster(ClusterConfiguration.java:62)[286:io.subutai.plugin.appscale.impl:4.0.0.RC14-SNAPSHOT]
    at io.subutai.plugin.appscale.impl.handler.ClusterOperationHandler.setupCluster(ClusterOperationHandler.java:185)[286:io.subutai.plugin.appscale.impl:4.0.0.RC14-SNAPSHOT]
    at io.subutai.plugin.appscale.impl.handler.ClusterOperationHandler.run(ClusterOperationHandler.java:81)[286:io.subutai.plugin.appscale.impl:4.0.0.RC14-SNAPSHOT]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_72-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_72-internal]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_72-internal]
2016-06-05 21:19:33,782 | ERROR | pool-98-thread-3 | ClusterConfiguration             | 286 - io.subutai.plugin.appscale.impl - 4.0.0.RC14-SNAPSHOT | Error to set proxy settings:
io.subutai.common.peer.PeerException: Error on adding reverse proxy: Command failed: time="2016-06-05 21:19:33" level=fatal msg="Reloading nginx, exit status 1"
, FAILED
    at io.subutai.core.localpeer.impl.LocalPeerImpl.addReverseProxy(LocalPeerImpl.java:2328)[181:io.subutai.core.localpeer.impl:4.0.0.RC14-SNAPSHOT]
    at Proxy6c7b9bfa_2e93_4648_bb95_be5a8c5ae3c1.addReverseProxy(Unknown Source)[:]
    at Proxy6c7b9bfa_2e93_4648_bb95_be5a8c5ae3c1.addReverseProxy(Unknown Source)[:]
    at Proxyda45de01_5b81_4111_8bb5_4c022278622f.addReverseProxy(Unknown Source)[:]
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.configureRH(ClusterConfiguration.java:147)[286:io.subutai.plugin.appscale.impl:4.0.0.RC14-SNAPSHOT]
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.installCluster(ClusterConfiguration.java:107)[286:io.subutai.plugin.appscale.impl:4.0.0.RC14-SNAPSHOT]
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.configureCluster(ClusterConfiguration.java:62)[286:io.subutai.plugin.appscale.impl:4.0.0.RC14-SNAPSHOT]
    at io.subutai.plugin.appscale.impl.handler.ClusterOperationHandler.setupCluster(ClusterOperationHandler.java:185)[286:io.subutai.plugin.appscale.impl:4.0.0.RC14-SNAPSHOT]
    at io.subutai.plugin.appscale.impl.handler.ClusterOperationHandler.run(ClusterOperationHandler.java:81)[286:io.subutai.plugin.appscale.impl:4.0.0.RC14-SNAPSHOT]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_72-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_72-internal]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_72-internal]
2016-06-05 21:19:33,782 | INFO  | pool-1-thread-9  | HubLoggerProcessor               | 193 - io.subutai.core.hubmanager.impl - 4.0.0.RC14-SNAPSHOT | RECEIVED:
:SubutaiLogEvent{timeStamp=1465161573781, loggerName='io.subutai.core.localpeer.impl.LocalPeerImpl', renderedMessage='Command failed: time="2016-06-05 21:19:33" level=fatal msg="Reloading nginx, exit status 1"
, FAILED', stackTrace='io.subutai.core.network.api.NetworkManagerException: Command failed: time="2016-06-05 21:19:33" level=fatal msg="Reloading nginx, exit status 1"
, FAILED
    at io.subutai.core.network.impl.NetworkManagerImpl.execute(NetworkManagerImpl.java:365)
    at io.subutai.core.network.impl.NetworkManagerImpl.setVlanDomain(NetworkManagerImpl.java:254)
    at Proxyf97daa60_0d35_4492_915f_a9362a4414d2.setVlanDomain(Unknown Source)
    at io.subutai.core.localpeer.impl.LocalPeerImpl.addReverseProxy(LocalPeerImpl.java:2321)
    at Proxy6c7b9bfa_2e93_4648_bb95_be5a8c5ae3c1.addReverseProxy(Unknown Source)
    at Proxy6c7b9bfa_2e93_4648_bb95_be5a8c5ae3c1.addReverseProxy(Unknown Source)
    at Proxyda45de01_5b81_4111_8bb5_4c022278622f.addReverseProxy(Unknown Source)
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.configureRH(ClusterConfiguration.java:147)
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.installCluster(ClusterConfiguration.java:107)
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.configureCluster(ClusterConfiguration.java:62)
    at io.subutai.plugin.appscale.impl.handler.ClusterOperationHandler.setupCluster(ClusterOperationHandler.java:185)
    at io.subutai.plugin.appscale.impl.handler.ClusterOperationHandler.run(ClusterOperationHandler.java:81)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
'}
2016-06-05 21:19:33,782 | INFO  | pool-98-thread-3 | ClusterConfiguration             | 286 - io.subutai.plugin.appscale.impl - 4.0.0.RC14-SNAPSHOT | Appscale installation done
2016-06-05 21:19:33,782 | INFO  | pool-1-thread-10 | HubLoggerProcessor               | 193 - io.subutai.core.hubmanager.impl - 4.0.0.RC14-SNAPSHOT | RECEIVED:
:SubutaiLogEvent{timeStamp=1465161573782, loggerName='io.subutai.plugin.appscale.impl.ClusterConfiguration', renderedMessage='Error to set proxy settings: ', stackTrace='io.subutai.common.peer.PeerException: Error on adding reverse proxy: Command failed: time="2016-06-05 21:19:33" level=fatal msg="Reloading nginx, exit status 1"
, FAILED
    at io.subutai.core.localpeer.impl.LocalPeerImpl.addReverseProxy(LocalPeerImpl.java:2328)
    at Proxy6c7b9bfa_2e93_4648_bb95_be5a8c5ae3c1.addReverseProxy(Unknown Source)
    at Proxy6c7b9bfa_2e93_4648_bb95_be5a8c5ae3c1.addReverseProxy(Unknown Source)
    at Proxyda45de01_5b81_4111_8bb5_4c022278622f.addReverseProxy(Unknown Source)
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.configureRH(ClusterConfiguration.java:147)
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.installCluster(ClusterConfiguration.java:107)
    at io.subutai.plugin.appscale.impl.ClusterConfiguration.configureCluster(ClusterConfiguration.java:62)
    at io.subutai.plugin.appscale.impl.handler.ClusterOperationHandler.setupCluster(ClusterOperationHandler.java:185)
    at io.subutai.plugin.appscale.impl.handler.ClusterOperationHandler.run(ClusterOperationHandler.java:81)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
'}`
# 

Test environment:
![image](https://cloud.githubusercontent.com/assets/7465404/15808297/224f4b08-2b96-11e6-935b-719aa7add479.png)

**Comment by eabyshev-zz** [comment]
@asanaliev I passed your case. AS installed with success and can reach web console.
SS version:
![screenshot from 2016-06-06 16 36 45](https://cloud.githubusercontent.com/assets/16954849/15819432/ec40d058-2c04-11e6-95a8-5df72908a40e.png)
Plugin version:
![screenshot from 2016-06-06 16 36 58](https://cloud.githubusercontent.com/assets/16954849/15819444/fc4eee6c-2c04-11e6-9b40-19bd926a330a.png)
